kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-pod-admission
  namespace: default
roleRef:
  kind: ClusterRole
  name: team-pods-admission-policy-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: system:serviceaccounts