apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdCluster"
metadata:
  name: "vault-etcd"
  namespace: security-system
  annotations:
   etcd.database.coreos.com/scope: clusterwide
spec:
  size: 3
  version: "3.2.16"
  pod:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "2379"
    nodeSelector:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: etcd_cluster
              operator: In
              values: ["vault-etcd"]
          topologyKey: kubernetes.io/hostname
    etcdEnv:
    - name: ETCD_AUTO_COMPACTION_RETENTION
      value: "1"
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 512Mi