apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: heapster-monitor
  namespace: pcit-commons
  labels:
    team: pcit
    environment: pcit-commons
spec:
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      k8s-app: heapster
  endpoints:
  - targetPort: http
    path: /metrics
    interval: 15s