apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rook-ceph-manager-monitor
  namespace: pcit-commons
  labels:
    team: pcit
    environment: pcit-commons
spec:
  namespaceSelector:
    matchNames:
      - rook
  selector:
    matchLabels:
      app: rook-ceph-mgr
      rook_cluster: rook
  endpoints:
  - port: http-metrics
    path: /metrics
    interval: 15s