apiVersion: v1
kind: ServiceAccount
metadata:
  name: pcit-node-exporter
  namespace: pcit-commons

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pcit-node-exporter
rules:
- apiGroups: ["authentication.k8s.io"]
  resources:
  - tokenreviews
  verbs: ["create"]
- apiGroups: ["authorization.k8s.io"]
  resources:
  - subjectaccessreviews
  verbs: ["create"]


---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pcit-node-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monigoring-core-node-exporter
subjects:
- kind: ServiceAccount
  name: pcit-node-exporter
  namespace: pcit-commons

---

apiVersion: v1
kind: Service
metadata:
  name: pcit-node-exporter
  namespace: pcit-commons
  labels:
    app: pcit-node-exporter
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: ClusterIP
  ports:
  - name: http-metrics
    port: 19101
    protocol: TCP
  selector:
    app: pcit-node-exporter

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pcit-node-exporter
  namespace: pcit-commons
  labels:
    app: pcit-node-exporter
spec:
  selector:
    matchLabels:
      app: pcit-node-exporter
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      name: pcit-node-exporter
      labels:
        app: pcit-node-exporter
    spec:
      serviceAccountName: pcit-node-exporter
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - image: quay.io/prometheus/node-exporter:v0.15.2
        args:
        - "--web.listen-address=0.0.0.0:19101"
        - "--path.procfs=/host/proc"
        - "--path.sysfs=/host/sys"
        ports:
        - containerPort: 19101
          hostPort: 19101
          name: http-metrics
        name: pcit-node-exporter
        resources:
          requests:
            memory: 30Mi
            cpu: 100m
          limits:
            memory: 50Mi
            cpu: 200m
        volumeMounts:
        - name: proc
          readOnly:  true
          mountPath: /host/proc
        - name: sys
          readOnly: true
          mountPath: /host/sys
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys