kind: ConfigMap
apiVersion: v1
metadata:
  name: ngrok-cfg
  namespace: kube-system
  labels:
    app: ngrok
data:
  ngrok.yaml: |
    web_addr: 0.0.0.0:4040
    log: stdout
    log_level: debug
    log_format: logfmt
    tunnels:
      istio:
        proto: http
        addr: istio-ingress.istio-system:80
---
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: ngrok
  namespace: kube-system
  labels:
    app: ngrok
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngrok
  template:
    metadata:
      labels:
        app: ngrok
    spec:
      containers:
      - image: luxas/ngrok:v2.1.18
        name: ngrok
        ports:
        - name: web
          containerPort: 4040
        args:
        - start
        - -config=/etc/ngrok/ngrok.yaml
        - istio
        volumeMounts:
          - name: ngrok-cfg
            mountPath: /etc/ngrok/
      volumes:
      - name: ngrok-cfg
        configMap:
          name: ngrok-cfg
---
apiVersion: v1
kind: Service
metadata:
  name: ngrok
  namespace: kube-system
spec:
  ports:
  - port: 80
    targetPort: 4040
  selector:
    app: ngrok