apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-apps-alert-manager
  namespace: backend-apps-commons

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backend-apps-alert-manager
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backend-apps-alert-manager
  namespace: backend-apps-commons
subjects:
- kind: ServiceAccount
  name: backend-apps-alert-manager
  namespace: backend-apps-commons
roleRef:
  kind: ClusterRole
  name: backend-apps-alert-manager
  apiGroup: "rbac.authorization.k8s.io"

---

apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: backend-apps-alert-manager
  namespace: backend-apps-commons
  labels:
    alertmanager: backend-apps-alert-manager
spec:
  replicas: 3
  version: v0.14.0
  serviceAccountName: backend-apps-alert-manager
  externalUrl: "https://alermanager.com"
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: "alertmanager"
                operator: In
                values:
                - backend-apps-alert-manager
          topologyKey: "kubernetes.io/hostname"
  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      cpu: 50m
      memory: 50Mi

---

apiVersion: v1
kind: Service
metadata:
  name: backend-apps-alert-manager
  namespace: backend-apps-commons
  labels:
    alertmanager: backend-apps-alert-manager
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 9093
  selector:
    alertmanager: backend-apps-alert-manager
