apiVersion: v1
kind: LimitRange
metadata:
  name: backend-apps-staging-limit-ranges
  namespace: backend-apps-staging
  labels:
    team: backend-apps
spec:
  limits:
  - type: PersistentVolumeClaim
    max:
      storage: 5Gi
    min:
      storage: 1Gi