apiVersion: v1
kind: LimitRange
metadata:
  name: rook-limit-ranges
  namespace: rook
  labels:
    team: rook
spec:
  limits:
  - type: PersistentVolumeClaim
    max:
      storage: 10Gi
    min:
      storage: 1Gi