kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
    limits:
      storage: 1Gi
  storageClassName: rook-block
---
kind: Service
apiVersion: v1
metadata:
  name: postgresql
spec:
  type: ClusterIP
  selector:
    app: postgresql
  ports:
    - port: 3306
      protocol: TCP
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: postgresql
  labels:
    app: postgresql
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      name: postgresql
      labels:
        app: postgresql
        version: 10.0
    spec:
      terminationGracePeriodSeconds: 60
      volumes:
        - name: postgresql
          persistentVolumeClaim:
            claimName: postgresql
      containers:
        - name: postgresql
          image: postgres:10.0
#          args:
#            - "--bind-address=0.0.0.0"
#            - "--ignore-db-dir=*"
#            - "--explicit_defaults_for_timestamp"
#          securityContext:
#            runAsUser: 999
          resources:
            requests:
              memory: 1Gi
              cpu: 1
          env:
            - name: POSTGRES_PASSWORD
              value: somepassword
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 600
            periodSeconds: 2
            failureThreshold: 5
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: postgresql
              mountPath: /var/lib/postgresql/data

