apiVersion: v1
kind: ResourceQuota
metadata:
  name: security-system-resource-quotas
  namespace: security-system
  labels:
    team: pcit
spec:
  hard:
    persistentvolumeclaims: "5"
    requests.storage: "10Gi"