apiVersion: v1
kind: LimitRange
metadata:
  name: rook-system-limit-ranges
  namespace: rook-system
  labels:
    team: rook-system
spec:
  limits:
  - type: PersistentVolumeClaim
    max:
      storage: 10Gi
    min:
      storage: 1Gi