apiVersion: v1
kind: LimitRange
metadata:
  name: production-limit-ranges
  namespace: production
  labels:
    team: pcit
spec:
  limits:
  - type: PersistentVolumeClaim
    max:
      storage: 5Gi
    min:
      storage: 1Gi