apiVersion: v1
kind: Service
metadata:
  name: wrk
  labels:
    app: wrk
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: wrk
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wrk
  labels:
    app: wrk
    version: v4
  annotations:
    sidecar.istio.io/inject: "true"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wrk
        version: v4
    spec:
      containers:
      - name: wrk
        image: klaemo/wrk
        command: ["/bin/sleep","infinity"]
        imagePullPolicy: IfNotPresent
---
