apiVersion: v1
kind: LimitRange
metadata:
  name: backend-apps-production-limit-ranges
  namespace: backend-apps-production
  labels:
    team: backend-apps
spec:
  limits:
  - type: PersistentVolumeClaim
    max:
      storage: 5Gi
    min:
      storage: 1Gi