kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-nfs-claim
  annotations:
    #volume.beta.kubernetes.io/storage-class: "default"
    volume.beta.kubernetes.io/mount-options: "nfsvers=3,rw"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
    limits:
      storage: 1Gi
  storageClassName: default
