kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kuard-pod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-block
  resources:
    requests:
      storage: 2Gi
    limits:
      storage: 2Gi
---
kind: Service
apiVersion: v1
metadata:
  name: kuard-pod
spec:
  type: LoadBalancer
  selector:
    app: kuard-pod
  ports:
    - port: 8080
      protocol: TCP
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: kuard-pod
  labels:
    app: kuard-pod
spec:
  replicas: 1
  minReadySeconds: 60
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 150
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kuard-pod
  template:
    metadata:
      labels:
        app: kuard-pod
    spec:
      terminationGracePeriodSeconds: 60
      volumes:
        - name: kuard-pod
          persistentVolumeClaim:
            claimName: kuard-pod
      containers:
        - name: kuard-pod
          image: gcr.io/kuar-demo/kuard-amd64:2
          resources:
            requests:
              memory: 200Mi
              cpu: 100m
          env:
            - name: HELLO
              value: world
          livenessProbe:
            httpGet:
              path: /healthy
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 2
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 2
            failureThreshold: 3
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: kuard-pod
              mountPath: /kuard-pod
              subPath: kube-mysql

