apiVersion: v1
kind: Service
metadata:
  name: prod-services
  labels:
    target: prod-services
    ver: "1"
    app: prod-services
    env: prod
spec:
  type: ClusterIP
  selector:
    env: prod
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
