kind: PersistentVolume
apiVersion: v1
metadata:
  name: database
  labels:
    volume: mysql-volume
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  nfs:
    server: 10.12.1.55
    path: "/mnt/tank2/bi-jenkins"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
    limits:
      storage: 1Gi
  selector:
    matchLabels:
      volume: mysql-volume
---
kind: Service
apiVersion: v1
metadata:
  name: mysql
spec:
  type: LoadBalancer
  selector:
    app: mysql
  ports:
    - port: 3306
      protocol: TCP
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 60
      volumes:
        - name: database
          persistentVolumeClaim:
            claimName: database
      containers:
        - name: mysql
          image: mysql:5.7
          args:
            - "--bind-address=0.0.0.0"
            - "--ignore-db-dir=*"
            - "--explicit_defaults_for_timestamp"
          securityContext:
            runAsUser: 999
          resources:
            requests:
              memory: 3Gi
              cpu: 2
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: somepassword
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 600
            periodSeconds: 2
            failureThreshold: 5
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: database
              mountPath: /var/lib/mysql
              subPath: kube-mysql

