apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: umomi-hpa
  labels:
    app: umomi
spec:
  minReplicas: 3
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: ReplicaSet
    name: umomi
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 20
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 5

---

apiVersion: v1
kind: Service
metadata:
  name: umomi-service
  labels:
    app: umomi
    env: prod
    ver: 1.1.0
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer
  selector:
    app: umomi
    env: prod
    ver: 1.1.0

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: umomi
  namespace: default
  labels:
    app: umomi
    ver: 1.1.0
    env: prod
    where: laptop-at-home
  annotations:
    sidecar.istio.io/inject: "true"
spec:
  selector:
    matchLabels:
      app: umomi
  template:
    metadata:
      name: umomi
      labels:
        app: umomi
        env: prod
        ver: 1.1.0
    spec:
      containers:
      - name: umomi
        image: gcr.io/kuar-demo/kuard-amd64:2
        ports: 
        - name: http
          protocol: TCP
          containerPort: 8080
        resources:
          requests:
            cpu: 500m
            memory: 128Mi
          limits:
            cpu: 900m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
          failureThreshold: 3
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /healthy
            port: 8080
          initialDelaySeconds: 0
          periodSeconds: 3
          timeoutSeconds: 1
          failureThreshold: 3
          successThreshold: 1
