apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:kube-apiserver-to-kubelet
rules:
  - apiGroups:
      - ""
    resources:
      - nodes/proxy
      - nodes/stats
      - nodes/log
      - nodes/spec
      - nodes/metrics
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:kube-apiserver
  namespace: ""
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kube-apiserver-to-kubelet
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: kubernetes
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: system:node:k8s-server-1
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: k8s-node-1
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: k8s-node-2
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: k8s-node-3

---

#apiVersion: rbac.authorization.k8s.io/v1
#kind: ClusterRole
#metadata:
#  annotations:
#    rbac.authorization.kubernetes.io/autoupdate: "true"
#  labels:
#    kubernetes.io/bootstrapping: rbac-defaults
#  name: system:kube-proxy-to-kubelet
#rules:
#  - apiGroups:
#      - ""
#    resources:
#      - nodes
#      - nodes/proxy
#      - nodes/stats
#      - nodes/log
#      - nodes/spec
#      - nodes/metrics
#    verbs:
#      - "*"
#
#---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: ClusterRoleBinding
#metadata:
#  name: system:kube-proxy
#roleRef:
#  apiGroup: rbac.authorization.k8s.io
#  kind: ClusterRole
#  name: system:kube-proxy-to-kubelet
#subjects:
#  - apiGroup: rbac.authorization.k8s.io
#    kind: User
#    name: k8s-server-1-kube-proxy
#  - apiGroup: rbac.authorization.k8s.io
#    kind: User
#    name: k8s-server-2-kube-proxy
#  - apiGroup: rbac.authorization.k8s.io
#    kind: User
#    name: k8s-server-3-kube-proxy
#  - apiGroup: rbac.authorization.k8s.io
#    kind: User
#    name: k8s-node-1-kube-proxy
#  - apiGroup: rbac.authorization.k8s.io
#    kind: User
#    name: k8s-node-2-kube-proxy
#  - apiGroup: rbac.authorization.k8s.io
#    kind: User
#    name: k8s-node-3-kube-proxy

