kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: developers-role
  namespace: default
rules:
- apiGroups: ["*"]
  resources: ["services"]
  verbs: ["get","watch","list"]
- apiGroups: ["*"]
  resources: ["pods"]
  verbs: ["get","watch","list"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: developers-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: developers-role
subjects:
- kind: Group
  name: developers
  namespace: default

---