---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pcit-grafana
  namespace: pcit-commons
  labels:
    app: pcit-grafana
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
    limits:
      storage: 5Gi
  storageClassName: fast

---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: pcit-grafana
  namespace: pcit-commons
  labels:
    app: pcit-grafana
spec:
  minReplicas: 1
  maxReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pcit-grafana
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 90
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 90

---

kind: ServiceAccount
apiVersion: v1
metadata:
  name: pcit-grafana
  namespace: pcit-commons

---

apiVersion: v1
kind: Service
metadata:
  name: pcit-grafana
  namespace: pcit-commons
  labels:
    app: pcit-grafana
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    app: pcit-grafana

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: pcit-grafana-config
  namespace: pcit-commons
data:
  config.ini: |
    [database]
    path = /data/grafana.db

    [paths]
    data = /data
    logs = /data/log
    plugins = /data/plugins

    [session]
    provider = memory

    [auth.basic]
    enabled = true

    [auth.anonymous]
    enabled = false

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pcit-grafana
  namespace: pcit-commons
  labels:
    app: pcit-grafana
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  selector:
    matchLabels:
      app: pcit-grafana
  template:
    metadata:
      labels:
        app: pcit-grafana
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      containers:
      - name: grafana
        image: quay.io/coreos/monitoring-grafana:5.0.0
        volumeMounts:
        - name: grafana-storage
          mountPath: /data
        - name: grafana-datasources
          mountPath: /grafana/conf/provisioning/datasources
        - name: grafana-dashboards
          mountPath: /grafana/conf/provisioning/dashboards
        - name: grafana-dashboard-definitions-0
          mountPath: /grafana-dashboard-definitions/0
        - name: grafana-dashboard-definitions-1
          mountPath: /grafana-dashboard-definitions/1
        - name: grafana-dashboard-definitions-2
          mountPath: /grafana-dashboard-definitions/2
        - name: grafana-dashboard-definitions-3
          mountPath: /grafana-dashboard-definitions/3
        - name: grafana-config
          mountPath: /grafana/conf/config.ini
          subPath: config.ini
        ports:
        - name: web
          containerPort: 3000
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 200Mi
            cpu: 200m
      volumes:
      - name: grafana-storage
        emptyDir:
      - name: grafana-datasources
        configMap:
          name: pcit-grafana-datasources
      - name: grafana-dashboards
        configMap:
          name: pcit-grafana-dashboards
      - name: grafana-dashboard-definitions-0
        configMap:
          name: pcit-grafana-dashboard-definitions-0
      - name: grafana-dashboard-definitions-1
        configMap:
          name: pcit-grafana-dashboard-definitions-1
      - name: grafana-dashboard-definitions-2
        configMap:
          name: pcit-grafana-dashboard-definitions-2
      - name: grafana-dashboard-definitions-3
        configMap:
          name: pcit-grafana-dashboard-definitions-3
      - name: grafana-config
        configMap:
          name: pcit-grafana-config