apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kube-system-firewall
  namespace: kube-system
  labels:
    team: pcit
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels: {}
    ports:
    - {}
  egress:
  - to:
    - namespaceSelector:
        matchLabels: {}
    ports:
    - {}

