apiVersion: v1
kind: LimitRange
metadata:
  name: kube-system-limit-ranges
  namespace: kube-system
  labels:
    team: kube-system
spec:
  limits:
  - type: PersistentVolumeClaim
    max:
      storage: 10Gi
    min:
      storage: 1Gi