kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: security-system-pod-admission
  namespace: security-system
roleRef:
  kind: ClusterRole
  name: system-pods-admission-policy-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: system:serviceaccounts