kind: Service
apiVersion: v1
metadata:
  name: dia-jenkins-proxy
  labels:
    app: dia-jenkins-proxy
    proxy-target: dia-jenkins
spec:
  clusterIP: None
  ports:
    - name: http
      protocol: TCP
      port: 8080
---
kind: Endpoints
apiVersion: v1
metadata:
  name: dia-jenkins-proxy
  labels:
    app: dia-jenkins-proxy
subsets:
  - addresses:
    - ip: 10.12.1.90
    ports:
      - name: http
        protocol: TCP
        port: 8080