apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nginx-fast-storage
  namespace: default
  labels:
    app: nginx
    ssd: "true"
spec:
  minReadySeconds: 10
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: nginx
        ssd: "true"
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      nodeSelector:
        ssd: "true"
      containers:
      - name: nginx
        image: nginx:1.13.5
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            memory: 200Mi
        ports:
        - name: http
          protocol: TCP
          containerPort: 80





