apiVersion: apps/v1
kind: Deployment
metadata:
  name: tutum-dnsutils
spec:
  selector:
    matchLabels:
      app: tutum-dnsutils
  replicas: 1
  template:
    metadata:
      labels:
        app: tutum-dnsutils
    spec:
      hostNetwork: true
      containers:
      - name: dnsutils
        image: tutum/dnsutils
        command: ["sleep", "3600"]


