apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: umueze
  namespace: default
  labels:
    app: umueze
    ver: 1.1.0
    env: prod
    where: laptop-at-home
spec:
  replicas: 3
  template:
    metadata:
      name: umueze
      labels:
        app: umueze
        env: prod
        ver: 1.1.0
    spec:
      containers:
      - name: umueze
        image: gcr.io/kuar-demo/kuard-amd64:2
        ports: 
        - name: http
          protocol: TCP
          containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 128Mi
          limits:
            cpu: 10m
            memory: 256Mi
        
