kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: backend-apps-production-role
  namespace: backend-apps-production
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-apps-production-read-only-binding
  namespace: backend-apps-production
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: backend-apps-production-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: backend-apps-production

---
