apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: staging-firewall
  namespace: staging
  labels:
    team: pcit
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          env: monitoring-core
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          env: security-system
  - to:
    - namespaceSelector:
        matchLabels:
          env: kube-system
    ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP

