apiVersion: v1
kind: LimitRange
metadata:
  name: istio-system-limit-ranges
  namespace: istio-system
  labels:
    team: istio-system
spec:
  limits:
  - type: PersistentVolumeClaim
    max:
      storage: 10Gi
    min:
      storage: 1Gi