apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-apps-grafana-datasources
  namespace: backend-apps-commons
data:
  prometheus.yaml: |+
    datasources:
     - name: prometheus
       type: prometheus
       access: proxy
       org_id: 1
       url: http://backend-apps-prometheus.backend-apps-commons:9090
       version: 1
       editable: false
     - name: influxdb
       type: influxdb
       access: proxy
       org_id: 1
       url: http://monitoring-influxdb.kube-system:8086
       version: 1
       editable: false
       database: k8s
