---
apiVersion: v1
kind: Service
metadata:
  name: arangodb-agents
spec:
  ports:
    - port: 8529
      targetPort: 8529
  clusterIP: None
  selector:
    name: arangodb
    role: agent
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: arangodb-agent
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  selector:
    matchLabels:
      name: arangodb
      role: agent
  serviceName: "arangodb-agents"
  replicas: 3
  template:
    metadata:
      labels:
        name: arangodb
        role: agent
        version: 3.3.7
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: arangodb
          image: arangodb/arangodb:3.3.7
          env:
            - name: IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ARANGO_NO_AUTH
              value: "1"
          ports:
            - containerPort: 8529
          volumeMounts:
            - mountPath: /var/lib/arangodb3
              name: arangodb-agency-data
          args:
            - --server.authentication
            - "false"
            - --server.endpoint
            - tcp://0.0.0.0:8529
            - --agency.activate
            - "true"
            - --agency.size
            - "3"
            - --agency.supervision
            - "true"
            - --agency.my-address
            - tcp://$(IP):8529
            - --agency.endpoint
            - tcp://arangodb-agent-0.arangodb-agents.default.svc.cluster.local:8529
  volumeClaimTemplates:
    - metadata:
        name: arangodb-agency-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: rook-block
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: arangodb-coords
spec:
  ports:
    - port: 8529
      targetPort: 8529
  type: ClusterIP
  selector:
    name: arangodb
    role: coordinator
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: arangodb-coord
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  selector:
    matchLabels:
      name: arangodb
      role: coordinator
  serviceName: "arangodb-coords"
  replicas: 2
  template:
    metadata:
      labels:
        name: arangodb
        role: coordinator
        version: 3.3.7
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: arangodb
          image: arangodb/arangodb:3.3.7
          env:
            - name: IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ARANGO_NO_AUTH
              value: "1"
          ports:
            - containerPort: 8529
          volumeMounts:
            - mountPath: /var/lib/arangodb3
              name: arangodb-coords-data
          args:
            - --server.authentication
            - "false"
            - --server.endpoint
            - tcp://0.0.0.0:8529
            - --cluster.my-role
            - COORDINATOR
            - --cluster.my-local-info
            - "$(IP)"
            - --cluster.my-address
            - tcp://$(IP):8529
            - --cluster.agency-endpoint
            - tcp://arangodb-agent-0.arangodb-agents.default.svc.cluster.local:8529
  volumeClaimTemplates:
    - metadata:
        name: arangodb-coords-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: rook-block
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: arangodb-dbs
spec:
  ports:
    - port: 8529
      targetPort: 8529
  type: ClusterIP
  selector:
    name: arangodb
    role: dbserver
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: arangodb-db
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  selector:
    matchLabels:
      name: arangodb
      role: dbserver
  serviceName: "arangodb-dbs"
  replicas: 3
  template:
    metadata:
      labels:
        name: arangodb
        role: dbserver
        version: 3.3.7
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: arangodb
          image: arangodb/arangodb:3.3.7
          env:
            - name: IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ARANGO_NO_AUTH
              value: "1"
          ports:
            - containerPort: 8529
          volumeMounts:
            - mountPath: /var/lib/arangodb3
              name: arangodb-db-data
            - mountPath: /var/lib/arangodb3-apps
              name: arangodb-db-apps
          args:
            - --server.authentication
            - "false"
            - --server.endpoint
            - tcp://0.0.0.0:8529
            - --cluster.my-role
            - PRIMARY
            - --cluster.my-local-info
            - "$(IP)"
            - --cluster.my-address
            - tcp://$(IP):8529
            - --cluster.agency-endpoint
            - tcp://arangodb-agent-0.arangodb-agents.default.svc.cluster.local:8529
  volumeClaimTemplates:
    - metadata:
        name: arangodb-db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: rook-block
        resources:
          requests:
            storage: 5Gi
    - metadata:
        name: arangodb-db-apps
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: rook-block
        resources:
          requests:
            storage: 1Gi
